import type {Metadata} from "next";
import {} from "next/font/google";
import "../globals.css";
import {Sidebar} from "@/components/Sidebar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (


        <div className={"flex justify-center items-center h-screen w-full bg-white p-4"}>
            <div className={"flex bg-linear-to-br from-[#e2e8f0] to-[#cbd5e1] backdrop-blur-xl border-white rounded-xl shadow-2xl h-full w-full p-4"}>
                    <Sidebar/>
                    <div className="w-4/5 flex-1  h-full bg-transparent overflow-y-auto p-6  min-h-full border-none">
                        {children}
                    </div>
                </div>
            </div>

    );
}
