import type {Metadata} from "next";
import {} from "next/font/google";
import "../globals.css";
import {Sidebar} from "@/components/Sidebar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (



            <div className={"flex bg-white shadow-md h-full w-full p-3"}>
                    <Sidebar/>
                    <div className=" flex-1  h-full bg-transparent pl-3 overflow-y-auto min-h-full border-none">
                        {children}
                    </div>
                </div>


    );
}
